export const GET_DEFAULT_TRANSACTION_REQUEST = "GET_DEFAULT_TRANSACTION_REQUEST";
export const GET_DEFAULT_TRANSACTION_SUCCESS = "GET_DEFAULT_TRANSACTION_SUCCESS";
export const GET_DEFAULT_TRANSACTION_FAIL = "GET_DEFAULT_TRANSACTION_FAIL";
