export const GET_EXPECTED_TRANSACTION_REQUEST = "GET_EXPECTED_TRANSACTION_REQUEST";
export const GET_EXPECTED_TRANSACTION_SUCCESS = "GET_EXPECTED_TRANSACTION_SUCCESS";
export const GET_EXPECTED_TRANSACTION_FAIL = "GET_EXPECTED_TRANSACTION_FAIL";
