export const GET_SUCCESSFUL_TRANSACTION_REQUEST = "GET_SUCCESSFUL_TRANSACTION_REQUEST";
export const GET_SUCCESSFUL_TRANSACTION_SUCCESS = "GET_SUCCESSFUL_TRANSACTION_SUCCESS";
export const GET_SUCCESSFUL_TRANSACTION_FAIL = "GET_SUCCESSFUL_TRANSACTION_FAIL";
